### ISSUE TITLE
Tab and '`' navigation

### ISSUE THREAD

**Issue by ris58h** [ronyfadel/MissionControlPlusReleases#4]
I see that it's possible to navigate using arrow keys but navigation with `Tab` to switch apps and '`' to switch windows seems natural to me.

**Comment by ronyfadel** [comment]
How would you cycle though? the arrow keys work on a 2D grid. `Tab` isn't as natural (it's not a line or a circle, it's a grid. there is no "best" option)

**Comment by ris58h** [comment]
Good question. I believe it should work as `tab` navigation works in a browser or in macOS with `System Settings > Keyboard > Keyboard navigation`. Every `tab` press should move focus to the next element (window or window group in our case) and `shift+tab` to the previous one. It works even if UI elements aren't placed in a grid. We could start with topmost topleft element and go left-to-right top-to-bottom.

**Comment by khesed** [comment]
> Good question. I believe it should work as tab navigation works in a browser or in macOS with `System Settings > Keyboard > Keyboard navigation`. Every `tab` press should move focus to the next element (window or window group in our case) and `shift+tab` to the previous one. It works even if UI elements aren't placed in a grid. We could start with topmost topleft element and go left-to-right top-to-bottom.

I think this is an intuitive solution

**Comment by wtf403** [comment]
🙀 I really want this feature to be implemented! Using Tab to move around would be awesome. It would make things so much easier, especially when using fully keyboard navigation with yabai.
