### ISSUE TITLE
Closing Finder app over x which has more tabs open, ending in closing only 1 Tab an then it Zoom out the Finder app and breaks MissionControl View!

### ISSUE THREAD

**Issue by Zorast** [ronyfadel/MissionControlPlusReleases#6]
Closing Finder app over x which has more tabs open, ending in closing only 1 Tab an then it Zoom out the Finder app and breaks MissionControl View!

**Comment by ronyfadel** [comment]
Yeah, not ideal I know :/
I'll see if I can do something about it.

**Comment by Zorast** [comment]
Thanks ! :)
