### ISSUE TITLE
Feature request: very large window title overlay

### ISSUE THREAD

**Issue by cdf1982** [ronyfadel/MissionControlPlusReleases#7]
Hi! I love Mission Control, and possibly you are the only person with enough knowledge about Mission Control to make a feature I've always wanted happen, so I ask you to consider this, if you have the time and you think it makes sense as an addition to the app.

When you move the mouse pointer over the windows in Mission Control, a small overlay shows the window title; it's not big at all, especially on large displays:
![2023-02-27 15_59_47](https://user-images.githubusercontent.com/11062186/221599176-d52f2d73-683f-463e-81a1-faa76aa5275f.png)

If it were possible, I'd love that overlay to be very large (almost as the window's width), to make it more glanceable.

Thanks in advance for considering this and thank you for your work!

**Comment by ronyfadel** [comment]
Not easy to do unfortunately. Too many edge cases.

**Comment by cdf1982** [comment]
I understand, and probably not a marketable feature. Thanks anyway!

If I'll ever have the time, I'll look into [this](https://developer.apple.com/library/archive/samplecode/UIElementInspector/Introduction/Intro.html) old sample project from Apple, which still compiles and work, and maybe put together something for my very niche needs.

Thanks again
