### ISSUE TITLE
Problem with Clicking & Dragging after Long Open-Duration

### ISSUE THREAD

**Issue by khesed** [ronyfadel/MissionControlPlusReleases#9]
After having the app open for a long time, there is a problem with clicking and dragging occasionally where it gets stuck enabled. This is resolved by middle-clicking the mouse.

The problem also occurs on a trackpad, but there is no middle click on a trackpad to solve the issue.

**Comment by khesed** [comment]
Also present in Sonoma

**Comment by Melonchanism** [comment]
not fixed
